# Сниппет: правило money + takeMoney
# Документация: https://abstractmenus.github.io/docs/ru/examples/snippets/rule-money
# Открыть: /ame_snip_money

include required(file("./plugins/AbstractMenus/menus/example/_shared/templates.conf"))

title: "&6Правило money"
size: 1
activators { command: "ame_snip_money" }

items: [
  {
    slot: 4
    material: GOLDEN_APPLE
    name: "&6Купить золотое яблоко"
    lore: ["&7Цена: &a$50"]
    click {
      rules { money: 50 }
      actions {
        takeMoney: 50
        itemAdd { material: GOLDEN_APPLE }
        sound: ${successSound}
      }
      denyActions: ${denyNoMoney}
    }
  }
  ${buttonClose} { slot: 8 }
]
