# Snippet: itemAdd action
# Docs: https://abstractmenus.github.io/docs/en/examples/snippets/action-give-item
# Open: /ame_snip_give

include required(file("./plugins/AbstractMenus/menus/example/_shared/templates.conf"))

title: "&6itemAdd Action"
size: 1
activators { command: "ame_snip_give" }

items: [
  {
    slot: 4
    material: WOODEN_PICKAXE
    name: "&aGive me a tool"
    lore: ["&7Click to receive a wooden pickaxe."]
    click {
      actions {
        itemAdd {
          material: WOODEN_PICKAXE
          name: "&aStarter Pickaxe"
        }
        sound: ${successSound}
      }
    }
  }
  ${buttonClose} { slot: 8 }
]
