import type { KeyDef } from './types';

export const ACTION_KEYS: KeyDef[] = [
  { name: 'message', scope: 'actions', valueType: 'string', description: 'Send a chat message to the player.' },
  { name: 'command', scope: 'actions', valueType: 'any', description: 'Run a console or player command. String or { cmd, as }.' },
  { name: 'chatInput', scope: 'actions', valueType: 'object', description: 'Prompt the player for chat input.' },
  { name: 'teleport', scope: 'actions', valueType: 'any', description: 'Teleport the player. Coordinates or named location.' },
  { name: 'itemAdd', scope: 'actions', valueType: 'object', description: 'Give an item to the player.' },
  { name: 'itemRemove', scope: 'actions', valueType: 'object', description: 'Remove an item from the player inventory.' },
  { name: 'sound', scope: 'actions', valueType: 'enum', enumRef: 'sounds', description: 'Play a Bukkit sound.' },
  { name: 'customSound', scope: 'actions', valueType: 'object', description: 'Play a custom (resource pack) sound.' },
  { name: 'addPotionEffect', scope: 'actions', valueType: 'object', description: 'Apply a potion effect.' },
  { name: 'removePotionEffect', scope: 'actions', valueType: 'string', description: 'Remove a potion effect by type.' },
  { name: 'openBook', scope: 'actions', valueType: 'object', description: 'Open a written book to the player.' },
  { name: 'openMenu', scope: 'actions', valueType: 'string', description: 'Open another menu by id.' },
  { name: 'closeMenu', scope: 'actions', valueType: 'any', description: 'Close the currently open menu.' },
  { name: 'refreshMenu', scope: 'actions', valueType: 'any', description: 'Refresh the current menu (re-render dynamic items).' },
  { name: 'refreshItem', scope: 'actions', valueType: 'object', description: 'Refresh a specific item by slot or id.' },
  { name: 'lpMetaSet', scope: 'actions', valueType: 'object', description: 'LuckPerms: set a meta key.' },
  { name: 'lpMetaRemove', scope: 'actions', valueType: 'object', description: 'LuckPerms: remove a meta key.' },
  { name: 'setVar', scope: 'actions', valueType: 'object', description: 'Set a personal player variable.' },
  { name: 'setVarp', scope: 'actions', valueType: 'object', description: 'Set a global (persistent) variable.' },
  { name: 'removeVar', scope: 'actions', valueType: 'string', description: 'Remove a personal variable.' },
  { name: 'removeVarp', scope: 'actions', valueType: 'string', description: 'Remove a global variable.' },
  { name: 'delay', scope: 'actions', valueType: 'object', description: 'Delay following actions by a duration.' },
  { name: 'bulk', scope: 'actions', valueType: 'object', description: 'Bulk container - groups actions and applies common modifiers.' },
  { name: 'randActions', scope: 'actions', valueType: 'list', description: 'Pick one of the listed action sets at random.' },
  { name: 'setSkin', scope: 'actions', valueType: 'object', description: 'Apply a skin via SkinsRestorer.' },
  { name: 'addRecipe', scope: 'actions', valueType: 'string', description: 'Discover a crafting recipe for the player.' },
  { name: 'setItemProperty', scope: 'actions', valueType: 'object', description: 'Override an item property at runtime.' },
  { name: 'removeItemProperty', scope: 'actions', valueType: 'object', description: 'Clear a runtime property override.' },
  { name: 'setButton', scope: 'actions', valueType: 'object', description: 'Replace a menu button definition at runtime.' },
  { name: 'removeButton', scope: 'actions', valueType: 'object', description: 'Remove a menu button at runtime.' },
  { name: 'giveMoney', scope: 'actions', valueType: 'any', description: 'Give Vault money to the player.' },
  { name: 'takeMoney', scope: 'actions', valueType: 'any', description: 'Take Vault money from the player.' },
  { name: 'setGamemode', scope: 'actions', valueType: 'string', description: 'Set the player gamemode (CREATIVE/SURVIVAL/...).' },
  { name: 'bungeeConnect', scope: 'actions', valueType: 'string', description: 'Send the player to a BungeeCord server.' },
];
