# Блок-как-кнопка - активатор clickBlockType открывает меню при клике игрока по материалу
# Документация: https://abstractmenus.github.io/docs/ru/examples/world-integrations/block-as-button
# Открыть: правый клик по любому DIAMOND_BLOCK в мире
# Требует: -

include required(file("./plugins/AbstractMenus/menus/example/_shared/templates.conf"))

title: "&bАлмазный блок нажат на %activator_block_x%, %activator_block_y%, %activator_block_z%"
size: 1

activators {
  clickBlockType: ["DIAMOND_BLOCK"]
}

items: [
  {
    slot: 4
    material: DIAMOND
    name: "&bПриветствие"
    lore: [
      "&7Вы кликнули по алмазному блоку в"
      "&7мире &f%activator_block_world%&7."
      ""
      "&7Плейсхолдеры активатора дают вам"
      "&7координаты блока, мир, тип и т.д."
    ]
  }
  ${buttonClose} { slot: 8 }
]
