# Сниппет: правило permission
# Документация: https://abstractmenus.github.io/docs/ru/examples/snippets/rule-permission
# Открыть: /ame_snip_perm

include required(file("./plugins/AbstractMenus/menus/example/_shared/templates.conf"))

title: "&6Правило permission"
size: 1
activators { command: "ame_snip_perm" }

items: [
  {
    slot: 4
    material: DIAMOND
    name: "&bНаграда для админа"
    lore: ["&7Клик - только для админов."]
    click {
      rules { permission: "abstractmenus.admin" }
      actions {
        itemAdd { material: DIAMOND }
        sound: ${successSound}
        message: "&aАдминский алмаз получен."
      }
      denyActions: ${denyNoPerm}
    }
  }
  ${buttonClose} { slot: 8 }
]
