import { describe, test, expect } from 'vitest';
import {
  encodeShare,
  decodeShare,
  encodeWorkspace,
  decodeWorkspace,
  buildShareUrl,
  MAX_SHARE_URL_LEN,
} from './share-url';
import type { Workspace } from '../files/types';

describe('share-url round-trip', () => {
  test('empty string', () => {
    const enc = encodeShare('');
    expect(decodeShare(enc)).toBe('');
  });

  test('simple ASCII', () => {
    const text = 'title = "Hello"';
    expect(decodeShare(encodeShare(text))).toBe(text);
  });

  test('multi-byte (Russian)', () => {
    const text = 'title = "Привет мир"';
    expect(decodeShare(encodeShare(text))).toBe(text);
  });

  test('large config compresses smaller than raw', () => {
    const text = ('item = { material = STONE }\n').repeat(200);
    const enc = encodeShare(text);
    expect(decodeShare(enc)).toBe(text);
    expect(enc.length).toBeLessThan(text.length);
  });

  test('encoded uses URL-safe alphabet only', () => {
    const enc = encodeShare('a = 1\nb = 2');
    expect(/[+/=]/.test(enc)).toBe(false);
  });

  test('decode returns null on garbage', () => {
    expect(decodeShare('not-base64!!!')).toBeNull();
  });
});

describe('share-url v2 (workspace)', () => {
  const sampleWs = (): Workspace => ({
    v: 2,
    tabs: [
      { id: 'a', name: 'menu.conf', content: 'a = 1' },
      { id: 'b', name: 'defaults.conf', content: 'b = 2' },
    ],
    activeTabId: 'b',
  });

  test('encode/decode workspace round-trip preserves tab names + content', () => {
    const ws = sampleWs();
    const encoded = encodeWorkspace(ws);
    const decoded = decodeWorkspace(encoded);
    expect(decoded).not.toBeNull();
    expect(decoded?.v).toBe(2);
    expect(decoded?.tabs.map((t) => t.name)).toEqual(['menu.conf', 'defaults.conf']);
    expect(decoded?.tabs.map((t) => t.content)).toEqual(['a = 1', 'b = 2']);
    // ids are regenerated by the receiver - just check activeTabId points at a real tab
    const active = decoded?.tabs.find((t) => t.id === decoded?.activeTabId);
    expect(active?.name).toBe('defaults.conf');
  });

  test('decode v1 raw string falls back to single menu.conf tab', () => {
    const v1 = encodeShare('legacy = "ok"');
    const decoded = decodeWorkspace(v1);
    expect(decoded).not.toBeNull();
    expect(decoded?.tabs).toHaveLength(1);
    expect(decoded?.tabs[0].name).toBe('menu.conf');
    expect(decoded?.tabs[0].content).toBe('legacy = "ok"');
    expect(decoded?.activeTabId).toBe(decoded?.tabs[0].id);
  });

  test('decode garbage returns null', () => {
    expect(decodeWorkspace('!!!not-base64')).toBeNull();
  });

  test('decode empty string returns null', () => {
    expect(decodeWorkspace('')).toBeNull();
  });

  test('MAX_SHARE_URL_LEN is 8000', () => {
    expect(MAX_SHARE_URL_LEN).toBe(8000);
  });

  test('buildShareUrl returns ok for small workspace', () => {
    const r = buildShareUrl(sampleWs());
    expect(r.ok).toBe(true);
    if (r.ok) {
      expect(r.url).toContain('#config=');
      expect(r.url.length).toBeLessThanOrEqual(MAX_SHARE_URL_LEN);
    }
  });

  test('buildShareUrl returns tooLong for oversize workspace', () => {
    // Random ASCII so deflate can't crush it down past the URL limit.
    let blob = '';
    for (let i = 0; i < 50000; i++) {
      blob += String.fromCharCode(33 + Math.floor(Math.random() * 90));
    }
    const huge: Workspace = {
      v: 2,
      tabs: [{ id: 'a', name: 'menu.conf', content: blob }],
      activeTabId: 'a',
    };
    const r = buildShareUrl(huge);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.length).toBeGreaterThan(MAX_SHARE_URL_LEN);
  });
});
